version: '2'
services:

  music-metadata-service:
    container_name: music-metadata-service
    build:
      context: .
      dockerfile: Dockerfile
    image: music-metadata-service:latest
    ports:
      - "8080:8080"
    depends_on:
      - postgres


  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=music-metadata

